### ISSUE TITLE
Source code of Direct conv does not exit

### ISSUE THREAD

**Issue by limin2021** [chenxuhao/caffe-escoin#1]
Hi,
   I compile and run your code and read your source code.  I have two problems. Can you help me?
   1. When I run the code using the scripts provided by you, a segment fault is got.
   2. And I see all the source code whose name includes "esc". But it seems the implementations in these files are cuDNN's convolution implementation in fact.  Can you tell me where is the ESC convolution implementation?
Thanks a lot!

**Comment by jiahuiyang** [comment]
Hi, @limin2015 
I have the same question with you. Did author give you some answer?
Thanks

**Comment by limin2021** [comment]
Hi,
&nbsp; I finally find that the sparse convolution kernels are in the following files:&nbsp;
https://github.com/chenxuhao/caffe-escoin/blob/master/src/caffe/layers/conv_layer.cu
https://github.com/chenxuhao/caffe-escoin/blob/master/src/caffe/layers/base_conv_layer.cpp.
Hope it is useful for you.


Sincerely,
Min Li




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jiahuiyang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月10日(星期天) 凌晨0:07
收件人:&nbsp;"chenxuhao/caffe-escoin"<caffe-escoin@noreply.github.com&gt;;
抄送:&nbsp;"李敏"<1121099234@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [chenxuhao/caffe-escoin] Source code of Direct conv does not exit (#1)




Hi, @limin2015
 I have the same question with you. Did author give us some answer?
 Thanks

**Comment by jiahuiyang** [comment]
Thank you!  Help a lot.

**Comment by limin2021** [comment]
You are welcome. Are you doing work about sparse convolution? I am also interested in this topic.&nbsp;
You can add my wechat (account: 15501262386), maybe we can communicate more with each other.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jiahuiyang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 凌晨2:42
收件人:&nbsp;"chenxuhao/caffe-escoin"<caffe-escoin@noreply.github.com&gt;;
抄送:&nbsp;"李敏"<1121099234@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [chenxuhao/caffe-escoin] Source code of Direct conv does not exit (#1)




Thank you!  Help a lot.

**Comment by chenxuhao** [comment]
Sorry for the late reply. Did you find the cause of your segment fault?
